name: day-1-lgtm-stack
services:
  
  # grafana is for visualising metrics and logs
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_FEATURE_TOGGLES_ENABLE: "flameGraph traceqlEditor"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:3000/api/health | grep -q ok"]
      interval: 10s
      timeout: 5s
      retries: 10

  # prometheus is for collecting metrics and alerts
  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    command: ["--config.file=/etc/prometheus/prometheus.yml","--web.enable-remote-write-receiver"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]
  

  # loki is for collecting the logs
  loki:
    image: grafana/loki:3.7.7
    command: ["--config.file=/etc/loki/local-config.yaml"]
    ports: ["3100:3100"]
    
  # tempo is for tracing
  # grafana query tempo at port 3200, and opentelemetry sends traces to tempo at 4317 and 4318 port
  # tempo:
  #   image: grafana/tempo:2.10.8
  #   command: ["-config.file=/etc/tempo.yaml"]
  #   ports: ["3200:3200", "4317", "4318"]
  #   volumes: ["./tempo.yaml:/etc/tempo.yaml"]

  # mimir is like a metric storage and query the metrics via grafana, we can do this in
  # prometheus also but prometheus is not scalable so we can scrape data using prometheus
  # and then store it to mimir. 
  # mimir:
  #   image: grafana/mimir:latest
  #   command: ["-config.file=/etc/mimir.yaml","-target=all"]
  #   ports: ["9009:9009"]
  #   volumes: ["./mimir.yaml:/etc/mimir.yaml"]

  # pyroscope is for profileing
  pyroscope:
    image: grafana/pyroscope:2.3.0
    ports: ["4040:4040"]
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.160.0
    command: ["--config=/etc/otelcol/config.yaml"]
    ports: ["4317:4317","4318:4318"]
    volumes: ["./otel-collector/config.yaml:/etc/otelcol/config.yaml"]
    depends_on: [loki]
  alloy:
    image: grafana/alloy:latest
    command: ["run","--server.http.listen-addr=0.0.0.0:12345","/etc/alloy/config.alloy"]
    ports: ["12345":"12345"]
    volumes: ["./alloy/config.alloy:/etc/alloy/config.alloy"]
  # localstack:
  # api:
  # worker:
