# global is config that is applied globally on all jobs
global:
  scrape_interval: 15s  # collecting data
  evaluation_interval: 15s  # evaluate the alert rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: api
    metrics_path: /metrics
    static_configs:
      -targets: ["api:9464"]
  - job_name: worker
    metrics_path: /metrics
    static_configs:
      -tagets: ["worker:9464"]