apiversion: 1

# prometheus stores data, and grafana query the data and then display it.
# so here we are configuring grafana that you can query data from here
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
  - name: Tempo
    type: tempo
    url: http://tempo:3200